// grammarChecker.ts

import { generateOllamaResponse } from './ollamaService';
import type { AIPatternAuditResult, AIPatternLineHighlight } from '../types/cvTypes';

const SYSTEM_AUDITOR_PROMPT = `
You are an expert AI Detection and Resume Tone Auditor. Your job is to analyze resume text and identify phrases that sound overly automated, robotic, or generated by an LLM (such as generic buzzwords: "testament to", "spearheaded groundbreaking initiatives", "fostering synergy", "delving into", "seamlessly").

Analyze the provided text sentence-by-sentence.

Respond strictly in valid JSON format with the following structure:
{
  "overallAIScore": number, // 0 to 100 (0 = completely human, 100 = obvious AI)
  "status": "Human" | "Moderate AI" | "Heavy AI Pattern",
  "highlights": [
    {
      "lineIndex": number,
      "text": string,
      "severity": "green" | "yellow" | "red",
      "reason": string
    }
  ],
  "recommendations": [string]
}
Do not include markdown blocks or prose outside the JSON object.
`;

/**
 * Scans CV summary or experience text for AI markers and outputs line-by-line highlights.
 */
export async function auditAIPatterns(textToAudit: string): Promise<AIPatternAuditResult> {
  if (!textToAudit || textToAudit.trim().length === 0) {
    return {
      overallAIScore: 0,
      status: 'Human',
      highlights: [],
      recommendations: ['Text is empty.'],
    };
  }

  const prompt = `Audit this text for AI generation patterns and tone naturalness:\n\n${textToAudit}`;

  try {
    const jsonResponseText = await generateOllamaResponse({
      prompt,
      systemPrompt: SYSTEM_AUDITOR_PROMPT,
      jsonMode: true,
      temperature: 0.1,
    });

    const parsedData = JSON.parse(jsonResponseText);

    return {
      overallAIScore: typeof parsedData.overallAIScore === 'number' ? parsedData.overallAIScore : 15,
      status: parsedData.status || 'Human',
      highlights: Array.isArray(parsedData.highlights) ? parsedData.highlights : [],
      recommendations: Array.isArray(parsedData.recommendations) ? parsedData.recommendations : [],
    };
  } catch (err) {
    console.error('AI Audit Failed, falling back to local heuristic scan:', err);

    // Fallback heuristic if Ollama response needs fallback parsing
    const lines = textToAudit.split('. ').filter(Boolean);
    const highlights: AIPatternLineHighlight[] = lines.map((line, idx) => {
      const lower = line.toLowerCase();
      const isRed = lower.includes('testament') || lower.includes('spearheaded groundbreaking') || lower.includes('delve');
      const isYellow = lower.includes('fostered') || lower.includes('seamlessly') || lower.includes('key role');

      return {
        lineIndex: idx,
        text: line,
        severity: isRed ? 'red' : isYellow ? 'yellow' : 'green',
        reason: isRed ? 'High AI signature phrase detected' : isYellow ? 'Slightly generic tone' : 'Natural human sentence structure',
      };
    });

    const redCount = highlights.filter((h) => h.severity === 'red').length;
    const score = Math.min(100, Math.round((redCount / (lines.length || 1)) * 100 + 10));

    return {
      overallAIScore: score,
      status: score > 60 ? 'Heavy AI Pattern' : score > 30 ? 'Moderate AI' : 'Human',
      highlights,
      recommendations: ['Simplify transition phrases', 'Use quantifiable metrics instead of buzzwords'],
    };
  }
}